/* 1001 世界 3D · 内容配置层(纯数据,零依赖)
   各区域/世界的生成式配乐参数。tempo=速度, wave=音色, scale=音阶(半音),
   base=基频Hz, dens=音符密度, bass/pad/arp/swing/chirp=编排开关, vol=音量。 */
export const THEMES = {
  street:    { tempo: 96,  wave: 'triangle', scale: [0, 2, 4, 7, 9, 12],   base: 220, dens: .5, bass: true },
  art:       { tempo: 64,  wave: 'sine', scale: [0, 4, 7, 11, 12],   base: 330, dens: .38 },
  books:     { tempo: 70,  wave: 'sine', scale: [0, 2, 3, 7, 8, 12], base: 294, dens: .4 },
  birds:     { tempo: 84,  wave: 'sine', scale: [0, 2, 4, 7, 9],     base: 392, dens: .22, chirp: true },
  plants:    { tempo: 84,  wave: 'sine', scale: [0, 2, 4, 7, 9, 12], base: 262, dens: .45 },
  beers:     { tempo: 148, wave: 'square', scale: [0, 2, 4, 5, 7, 9], base: 196, dens: .8, bass: true, vol: .55 },
  fish:      { tempo: 52,  wave: 'sine', scale: [0, 3, 7, 10, 12],   base: 147, dens: .35, pad: true },
  jazz:      { tempo: 138, wave: 'sine', scale: [0, 3, 5, 6, 7, 10], base: 175, dens: .72, swing: true, bass: true },
  classical: { tempo: 106, wave: 'sine', scale: [0, 4, 7, 12, 16, 19], base: 262, dens: .85, arp: true },
  outdoor:   { tempo: 100, wave: 'triangle', scale: [0, 7, 12, 14, 19], base: 165, dens: .5, bass: true },
  truman:    { tempo: 118, wave: 'triangle', scale: [0, 4, 7, 9, 12], base: 294, dens: .68, bass: true, vol: .6 },
  shire:     { tempo: 90, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 220, dens: .6, bass: true },
  mordor:    { tempo: 58, wave: 'sine', scale: [0, 1, 3, 6, 7], base: 87, dens: .35, pad: true, vol: .85 },
  hogwarts:  { tempo: 96, wave: 'sine', scale: [0, 3, 5, 7, 8, 12], base: 392, dens: .6, arp: true, vol: .8 },
  mobydick:  { tempo: 76, wave: 'triangle', scale: [0, 3, 5, 7, 10], base: 165, dens: .55, bass: true, swing: true },
  stadium:   { tempo: 104, wave: 'square', scale: [0, 2, 4, 5, 7], base: 196, dens: .5, bass: true, vol: .5 },
  shanhai:   { tempo: 62, wave: 'sine', scale: [0, 2, 5, 7, 9], base: 131, dens: .4, pad: true },
  taoyuan:   { tempo: 76, wave: 'sine', scale: [0, 2, 4, 7, 9], base: 294, dens: .45 },
  nights:    { tempo: 96, wave: 'sine', scale: [0, 1, 4, 5, 7, 8, 11], base: 220, dens: .6, bass: true },
  nautdeep:  { tempo: 48, wave: 'sine', scale: [0, 3, 5, 7, 10], base: 110, dens: .3, pad: true, vol: .9 },
  b612:      { tempo: 70, wave: 'sine', scale: [0, 4, 7, 11, 14], base: 523, dens: .35, vol: .7 },
  jurassic:  { tempo: 56, wave: 'sine', scale: [0, 1, 6, 7], base: 98, dens: .3, pad: true, vol: .9 },
  huaguo:    { tempo: 112, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 262, dens: .7, bass: true, vol: .7 },
  alice:     { tempo: 88, wave: 'sine', scale: [0, 2, 3, 6, 8, 11], base: 349, dens: .55, arp: true, vol: .75 },
  chibi:     { tempo: 66, wave: 'square', scale: [0, 2, 5, 7, 10], base: 110, dens: .4, bass: true, vol: .45 },
  lanruo:    { tempo: 50, wave: 'sine', scale: [0, 1, 5, 6, 10], base: 196, dens: .3, pad: true, vol: .8 },
  liangshan: { tempo: 100, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 165, dens: .6, bass: true },
  siren:     { tempo: 60, wave: 'sine', scale: [0, 2, 3, 7, 8], base: 440, dens: .75, arp: true, vol: 1.1 },
  quixote:   { tempo: 108, wave: 'triangle', scale: [0, 1, 4, 5, 7, 8], base: 220, dens: .6, bass: true },
  chateau:   { tempo: 54, wave: 'sine', scale: [0, 2, 3, 5, 7], base: 147, dens: .35, pad: true },
  crusoe:    { tempo: 68, wave: 'sine', scale: [0, 2, 4, 7, 9], base: 196, dens: .35 },
  daguan:    { tempo: 72, wave: 'sine', scale: [0, 2, 4, 7, 9, 12], base: 330, dens: .5, arp: true, vol: .7 },
  purgatory: { tempo: 54, wave: 'sine', scale: [0, 3, 5, 7, 10, 12], base: 147, dens: .32, pad: true, vol: .82 },
  mystisle:  { tempo: 80, wave: 'triangle', scale: [0, 2, 3, 7, 9], base: 165, dens: .5, bass: true },
  treasure:  { tempo: 100, wave: 'sawtooth', scale: [0, 2, 4, 5, 7, 9], base: 147, dens: .6, bass: true, vol: .7 },
  mystery:   { tempo: 50, wave: 'sine', scale: [0, 1, 3, 6, 8], base: 131, dens: .3, pad: true, vol: .8 },
  tempest:   { tempo: 66, wave: 'triangle', scale: [0, 2, 3, 5, 7, 10], base: 196, dens: .45, pad: true },
  moreau:    { tempo: 58, wave: 'sawtooth', scale: [0, 1, 4, 6, 7], base: 110, dens: .32, bass: true, vol: .72 },
  dolphin:   { tempo: 70, wave: 'sine', scale: [0, 2, 4, 7, 9, 11], base: 262, dens: .38, vol: .72 },
  golding:   { tempo: 62, wave: 'square', scale: [0, 1, 3, 6, 7, 10], base: 123, dens: .4, bass: true, vol: .6 },
  utopia:    { tempo: 68, wave: 'triangle', scale: [0, 2, 4, 5, 7, 9, 11], base: 196, dens: .42, pad: true, vol: .72 },
  awaken:    { tempo: 48, wave: 'sine', scale: [0, 2, 4, 7, 9], base: 220, dens: .26, pad: true, vol: .78 },
  gulliver:  { tempo: 112, wave: 'triangle', scale: [0, 2, 4, 5, 7, 9], base: 294, dens: .55, arp: true, vol: .64 },
  neverland: { tempo: 92, wave: 'triangle', scale: [0, 2, 4, 7, 9, 12], base: 349, dens: .5, arp: true, vol: .68 },
  coral:     { tempo: 74, wave: 'sine', scale: [0, 2, 5, 7, 9], base: 233, dens: .4, vol: .72 },
  typee:     { tempo: 82, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 196, dens: .44, bass: true, vol: .68 },
  tahiti:    { tempo: 72, wave: 'triangle', scale: [0, 3, 5, 7, 10], base: 208, dens: .42, vol: .7 },
  dawntreader: { tempo: 78, wave: 'sine', scale: [0, 2, 4, 7, 9, 11, 12], base: 262, dens: .46, pad: true, vol: .76 },
  rainisle:  { tempo: 52, wave: 'sine', scale: [0, 2, 3, 5, 7, 8], base: 139, dens: .3, pad: true, vol: .66 },
  shutter:   { tempo: 46, wave: 'sawtooth', scale: [0, 1, 3, 6, 7, 9], base: 104, dens: .28, pad: true, vol: .58 },
};

/* 海洋文学带故事线(纯数据):每岛一条支线,挂在 lore 卡上,完成得 SB+⭐,列入航海日志 */
export const NI_QUESTS = {
  mys:  { lore: 'mystnemo',     btn: '🐚 循光潜入海底洞穴',   sb: 20, log: '🌋 神秘的恩人(神秘岛)',       pend: '⏳ 探海底洞穴',   done: '✅ 见过尼摩',   msg: '🐚 海底洞穴里,垂死的尼摩握住你的手:"这是我最后的秘密。" ⚡+20 · ⭐+1' },
  chr:  { lore: 'tensoldiers',  btn: '🪆 对着童谣推演真凶',   sb: 20, log: '🔪 童谣杀人(无人生还岛)',     pend: '⏳ 数一数瓷兵',   done: '✅ 真相已记',   msg: '🪆 死亡的顺序,与童谣一句句对上了——凶手,正是那个"最先离场"的人。 ⚡+20 · ⭐+1' },
  tmp:  { lore: 'prospero',     btn: '📖 劝法师折杖宽恕',     sb: 20, log: '⛈️ 折断法杖(暴风雨岛)',       pend: '⏳ 劝普洛斯彼罗', done: '✅ 仇已释怀',   msg: '📖 普洛斯彼罗把魔法书沉入海底:"稀有的德性,是宽恕,而非报复。" ⚡+20 · ⭐+1' },
  mor:  { lore: 'morlaw',       btn: '📜 随兽人诵一遍律法',   sb: 20, log: '🧪 兽人律法(莫罗博士岛)',     pend: '⏳ 参加诵法',     done: '✅ 律法已诵',   msg: '🧪 你随兽人齐诵:"我们不是人吗?"——念着念着,连你也分不清人兽的界线。 ⚡+20 · ⭐+1' },
  dol:  { lore: 'karana',       btn: '🦦 给受伤的海獭喂食',   sb: 15, log: '🐬 驯服獠牙(蓝色海豚岛)',     pend: '⏳ 结交海獭',     done: '✅ 有了朋友',   msg: '🦦 那只叫"獠牙"的海獭,终于肯从你手里接食——卡拉娜笑了,十八年来头一次。 ⚡+15 · ⭐+1' },
  fly:  { lore: 'flyconch',     btn: '🐚 吹响海螺重开集会',   sb: 20, log: '🐚 重整秩序(蝇王)',           pend: '⏳ 吹响海螺',     done: '✅ 火重新亮',   msg: '🐚 海螺一响,散去的孩子又围拢过来,信号火重新烧起——文明,续上了一口气。 ⚡+20 · ⭐+1' },
  uto:  { lore: 'utocity',      btn: '📖 记录理想国的制度',   sb: 15, log: '🏛️ 理想国见闻(乌托邦)',       pend: '⏳ 走访全城',     done: '✅ 已成手记',   msg: '🏛️ 六小时工作、无货币、金夜壶……你都记进本子。完美,还是可怕?留给读者判断。 ⚡+15 · ⭐+1' },
  hux:  { lore: 'moksha',       btn: '🧘 随八哥冥想此时此地', sb: 15, log: '🧘 注意·当下(帕拉岛)',       pend: '⏳ 练一次觉知',   done: '✅ 已然清醒',   msg: '🧘 "注意!此时,此地。"你跟着呼吸,第一次真正地在场。 ⚡+15 · ⭐+1' },
  gul:  { lore: 'lilliput',     btn: '🥚 调停敲蛋战争',       sb: 20, log: '👣 敲蛋和约(格列佛)',         pend: '⏳ 调停两党',     done: '✅ 已促和谈',   msg: '👣 你提议:今后各敲各的那头。大小端两派竟都答应了——天大的仇,原来起于一枚鸡蛋。 ⚡+20 · ⭐+1' },
  nvl:  { lore: 'lostchildren', btn: '✨ 想着快乐的事飞起来', sb: 15, log: '🧚 学会飞行(梦幻岛)',         pend: '⏳ 试着起飞',     done: '✅ 飞过一回',   msg: '✨ 你想起最快乐的一件事,脚尖离了地——原来长大,只是忘了怎么飞。 ⚡+15 · ⭐+1' },
  cor:  { lore: 'coralreef',    btn: '🤿 潜入水下岩洞',       sb: 15, log: '🐠 水下岩洞(珊瑚岛)',         pend: '⏳ 屏气下潜',     done: '✅ 探过秘洞',   msg: '🐠 你屏一口气潜到礁底,钻进一个连海盗都不知道的水下岩洞——里面亮得像撒了金子。 ⚡+15 · ⭐+1' },
  typ:  { lore: 'typeevalley',  btn: '🌴 助汤莫逃回海边',     sb: 20, log: '🌴 逃离山谷(泰皮)',           pend: '⏳ 寻机逃亡',     done: '✅ 已回大海',   msg: '🌴 趁法亚薇拨开禁忌绳,你和汤莫跳上独木舟冲向捕鲸船——文明还是野蛮,他终究做了选择。 ⚡+20 · ⭐+1' },
  tah:  { lore: 'studio',       btn: '🖼️ 在烧毁前抢一幅画',   sb: 20, log: '🎨 抢救杰作(画家岛)',         pend: '⏳ 冲进画室',     done: '✅ 留下一幅',   msg: '🎨 火舌舔上四壁前,你抢出一幅画——斯特里克兰要毁掉的乐园,总算留下一角。 ⚡+20 · ⭐+1' },
  daw:  { lore: 'worldsend',    btn: '🐭 送雷佩契普越浪墙',   sb: 20, log: '🐉 世界尽头(黎明踏浪号)',     pend: '⏳ 划向东方',     done: '✅ 已抵尽头',   msg: '🐭 你目送雷佩契普的小舟越过最后一道浪墙,驶入满是百合与光的国度——它到家了。 ⚡+20 · ⭐+1' },
  rain: { lore: 'missionary',   btn: '☔ 记下这场雨中的对峙', sb: 20, log: '🌧️ 帕果帕果的雨(雨岛)',       pend: '⏳ 旁观牧师',     done: '✅ 已见结局',   msg: '☔ 牧师倒在海滩,汤普森小姐冷笑一声"猪猡"。雨,还在下。你合上了本子。 ⚡+20 · ⭐+1' },
  shu:  { lore: 'shulighthouse',btn: '🗼 登灯塔查明真相',     sb: 20, log: '🌫️ 灯塔的真相(禁闭岛)',     pend: '⏳ 闯进灯塔',     done: '✅ 真相已明',   msg: '🗼 塔顶没有秘密实验,只有考利医生一句"欢迎回来"——那么,谁才是病人? ⚡+20 · ⭐+1' },
};
