/* 1001 世界 3D · 内容配置层(纯数据,零依赖)
   各区域/世界的生成式配乐参数。tempo=速度, wave=音色, scale=音阶(半音),
   base=基频Hz, dens=音符密度, bass/pad/arp/swing/chirp=编排开关, vol=音量。 */
export const THEMES = {
  street:    { tempo: 96,  wave: 'triangle', scale: [0, 2, 4, 7, 9, 12],   base: 220, dens: .5, bass: true },
  art:       { tempo: 64,  wave: 'sine', scale: [0, 4, 7, 11, 12],   base: 330, dens: .38 },
  books:     { tempo: 70,  wave: 'sine', scale: [0, 2, 3, 7, 8, 12], base: 294, dens: .4 },
  birds:     { tempo: 84,  wave: 'sine', scale: [0, 2, 4, 7, 9],     base: 392, dens: .22, chirp: true },
  plants:    { tempo: 84,  wave: 'sine', scale: [0, 2, 4, 7, 9, 12], base: 262, dens: .45 },
  beers:     { tempo: 148, wave: 'square', scale: [0, 2, 4, 5, 7, 9], base: 196, dens: .8, bass: true, vol: .55 },
  fish:      { tempo: 52,  wave: 'sine', scale: [0, 3, 7, 10, 12],   base: 147, dens: .35, pad: true },
  jazz:      { tempo: 138, wave: 'sine', scale: [0, 3, 5, 6, 7, 10], base: 175, dens: .72, swing: true, bass: true },
  classical: { tempo: 106, wave: 'sine', scale: [0, 4, 7, 12, 16, 19], base: 262, dens: .85, arp: true },
  outdoor:   { tempo: 100, wave: 'triangle', scale: [0, 7, 12, 14, 19], base: 165, dens: .5, bass: true },
  truman:    { tempo: 118, wave: 'triangle', scale: [0, 4, 7, 9, 12], base: 294, dens: .68, bass: true, vol: .6 },
  shire:     { tempo: 90, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 220, dens: .6, bass: true },
  mordor:    { tempo: 58, wave: 'sine', scale: [0, 1, 3, 6, 7], base: 87, dens: .35, pad: true, vol: .85 },
  hogwarts:  { tempo: 96, wave: 'sine', scale: [0, 3, 5, 7, 8, 12], base: 392, dens: .6, arp: true, vol: .8 },
  mobydick:  { tempo: 76, wave: 'triangle', scale: [0, 3, 5, 7, 10], base: 165, dens: .55, bass: true, swing: true },
  stadium:   { tempo: 104, wave: 'square', scale: [0, 2, 4, 5, 7], base: 196, dens: .5, bass: true, vol: .5 },
  shanhai:   { tempo: 62, wave: 'sine', scale: [0, 2, 5, 7, 9], base: 131, dens: .4, pad: true },
  taoyuan:   { tempo: 76, wave: 'sine', scale: [0, 2, 4, 7, 9], base: 294, dens: .45 },
  nights:    { tempo: 96, wave: 'sine', scale: [0, 1, 4, 5, 7, 8, 11], base: 220, dens: .6, bass: true },
  nautdeep:  { tempo: 48, wave: 'sine', scale: [0, 3, 5, 7, 10], base: 110, dens: .3, pad: true, vol: .9 },
  b612:      { tempo: 70, wave: 'sine', scale: [0, 4, 7, 11, 14], base: 523, dens: .35, vol: .7 },
  jurassic:  { tempo: 56, wave: 'sine', scale: [0, 1, 6, 7], base: 98, dens: .3, pad: true, vol: .9 },
  huaguo:    { tempo: 112, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 262, dens: .7, bass: true, vol: .7 },
  alice:     { tempo: 88, wave: 'sine', scale: [0, 2, 3, 6, 8, 11], base: 349, dens: .55, arp: true, vol: .75 },
  chibi:     { tempo: 66, wave: 'square', scale: [0, 2, 5, 7, 10], base: 110, dens: .4, bass: true, vol: .45 },
  lanruo:    { tempo: 50, wave: 'sine', scale: [0, 1, 5, 6, 10], base: 196, dens: .3, pad: true, vol: .8 },
  liangshan: { tempo: 100, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 165, dens: .6, bass: true },
  siren:     { tempo: 60, wave: 'sine', scale: [0, 2, 3, 7, 8], base: 440, dens: .75, arp: true, vol: 1.1 },
  quixote:   { tempo: 108, wave: 'triangle', scale: [0, 1, 4, 5, 7, 8], base: 220, dens: .6, bass: true },
  chateau:   { tempo: 54, wave: 'sine', scale: [0, 2, 3, 5, 7], base: 147, dens: .35, pad: true },
  crusoe:    { tempo: 68, wave: 'sine', scale: [0, 2, 4, 7, 9], base: 196, dens: .35 },
  daguan:    { tempo: 72, wave: 'sine', scale: [0, 2, 4, 7, 9, 12], base: 330, dens: .5, arp: true, vol: .7 },
  purgatory: { tempo: 54, wave: 'sine', scale: [0, 3, 5, 7, 10, 12], base: 147, dens: .32, pad: true, vol: .82 },
  mystisle:  { tempo: 80, wave: 'triangle', scale: [0, 2, 3, 7, 9], base: 165, dens: .5, bass: true },
  treasure:  { tempo: 100, wave: 'sawtooth', scale: [0, 2, 4, 5, 7, 9], base: 147, dens: .6, bass: true, vol: .7 },
  mystery:   { tempo: 50, wave: 'sine', scale: [0, 1, 3, 6, 8], base: 131, dens: .3, pad: true, vol: .8 },
  tempest:   { tempo: 66, wave: 'triangle', scale: [0, 2, 3, 5, 7, 10], base: 196, dens: .45, pad: true },
  moreau:    { tempo: 58, wave: 'sawtooth', scale: [0, 1, 4, 6, 7], base: 110, dens: .32, bass: true, vol: .72 },
  dolphin:   { tempo: 70, wave: 'sine', scale: [0, 2, 4, 7, 9, 11], base: 262, dens: .38, vol: .72 },
  golding:   { tempo: 62, wave: 'square', scale: [0, 1, 3, 6, 7, 10], base: 123, dens: .4, bass: true, vol: .6 },
  utopia:    { tempo: 68, wave: 'triangle', scale: [0, 2, 4, 5, 7, 9, 11], base: 196, dens: .42, pad: true, vol: .72 },
  awaken:    { tempo: 48, wave: 'sine', scale: [0, 2, 4, 7, 9], base: 220, dens: .26, pad: true, vol: .78 },
  gulliver:  { tempo: 112, wave: 'triangle', scale: [0, 2, 4, 5, 7, 9], base: 294, dens: .55, arp: true, vol: .64 },
  neverland: { tempo: 92, wave: 'triangle', scale: [0, 2, 4, 7, 9, 12], base: 349, dens: .5, arp: true, vol: .68 },
  coral:     { tempo: 74, wave: 'sine', scale: [0, 2, 5, 7, 9], base: 233, dens: .4, vol: .72 },
  typee:     { tempo: 82, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 196, dens: .44, bass: true, vol: .68 },
  tahiti:    { tempo: 72, wave: 'triangle', scale: [0, 3, 5, 7, 10], base: 208, dens: .42, vol: .7 },
  dawntreader: { tempo: 78, wave: 'sine', scale: [0, 2, 4, 7, 9, 11, 12], base: 262, dens: .46, pad: true, vol: .76 },
  rainisle:  { tempo: 52, wave: 'sine', scale: [0, 2, 3, 5, 7, 8], base: 139, dens: .3, pad: true, vol: .66 },
  shutter:   { tempo: 46, wave: 'sawtooth', scale: [0, 1, 3, 6, 7, 9], base: 104, dens: .28, pad: true, vol: .58 },
  capital:   { tempo: 54, wave: 'sine', scale: [0, 2, 3, 7, 8, 12], base: 175, dens: .3, pad: true, vol: .72 },
  gala:      { tempo: 72, wave: 'sine', scale: [0, 2, 4, 7, 9, 12], base: 175, dens: .36, vol: .7 },
  moai:      { tempo: 56, wave: 'sine', scale: [0, 2, 5, 7, 9, 12], base: 147, dens: .3, pad: true, vol: .78 },
  fogjail:   { tempo: 44, wave: 'sawtooth', scale: [0, 1, 3, 6, 8], base: 98, dens: .26, pad: true, vol: .56 },
  kilda:     { tempo: 58, wave: 'sine', scale: [0, 3, 5, 7, 10], base: 131, dens: .3, pad: true, vol: .7 },
  gunkan:    { tempo: 42, wave: 'sawtooth', scale: [0, 2, 3, 7, 10], base: 87, dens: .24, pad: true, vol: .58 },
  soco:      { tempo: 64, wave: 'sine', scale: [0, 2, 4, 6, 9, 11], base: 220, dens: .34, pad: true, vol: .7 },
  skell:     { tempo: 40, wave: 'sine', scale: [0, 5, 7, 12], base: 131, dens: .2, pad: true, vol: .66 },
  mada:      { tempo: 88, wave: 'triangle', scale: [0, 2, 4, 7, 9], base: 196, dens: .5, bass: true, vol: .66 },
  helena:    { tempo: 50, wave: 'sine', scale: [0, 2, 3, 7, 8], base: 165, dens: .28, pad: true, vol: .7 },
  komodo:    { tempo: 60, wave: 'triangle', scale: [0, 3, 5, 7, 10], base: 110, dens: .34, bass: true, vol: .62 },
  sanxian:   { tempo: 58, wave: 'sine', scale: [0, 2, 5, 7, 9, 12], base: 262, dens: .3, pad: true, vol: .74 },
  shixia:    { tempo: 72, wave: 'triangle', scale: [0, 3, 5, 7, 10], base: 147, dens: .4, bass: true, vol: .6 },
  taozhen:   { tempo: 76, wave: 'sine', scale: [0, 2, 4, 7, 9], base: 294, dens: .45, arp: true, vol: .7 },
  venezia:   { tempo: 84, wave: 'sine', scale: [0, 2, 4, 5, 7, 11], base: 294, dens: .5, arp: true, vol: .7 },
  saga:      { tempo: 52, wave: 'triangle', scale: [0, 2, 3, 7, 10], base: 98, dens: .3, pad: true, bass: true, vol: .7 },
  atl:       { tempo: 60, wave: 'sine', scale: [0, 3, 5, 7, 8, 12], base: 220, dens: .32, pad: true, vol: .72 },
};

/* 海洋文学带故事线(纯数据):每岛一条支线,挂在 lore 卡上,完成得 SB+⭐,列入航海日志 */
export const NI_QUESTS = {
  mys:  { lore: 'mystnemo',     btn: '🐚 循光潜入海底洞穴',   sb: 20, log: '🌋 神秘的恩人(神秘岛)',       pend: '⏳ 探海底洞穴',   done: '✅ 见过尼摩',   msg: '🐚 海底洞穴里,垂死的尼摩握住你的手:"这是我最后的秘密。" ⚡+20 · ⭐+1' },
  chr:  { lore: 'tensoldiers',  btn: '🪆 对着童谣推演真凶',   sb: 20, log: '🔪 童谣杀人(无人生还岛)',     pend: '⏳ 数一数瓷兵',   done: '✅ 真相已记',   msg: '🪆 死亡的顺序,与童谣一句句对上了——凶手,正是那个"最先离场"的人。 ⚡+20 · ⭐+1' },
  tmp:  { lore: 'prospero',     btn: '📖 劝法师折杖宽恕',     sb: 20, log: '⛈️ 折断法杖(暴风雨岛)',       pend: '⏳ 劝普洛斯彼罗', done: '✅ 仇已释怀',   msg: '📖 普洛斯彼罗把魔法书沉入海底:"稀有的德性,是宽恕,而非报复。" ⚡+20 · ⭐+1' },
  mor:  { lore: 'morlaw',       btn: '📜 随兽人诵一遍律法',   sb: 20, log: '🧪 兽人律法(莫罗博士岛)',     pend: '⏳ 参加诵法',     done: '✅ 律法已诵',   msg: '🧪 你随兽人齐诵:"我们不是人吗?"——念着念着,连你也分不清人兽的界线。 ⚡+20 · ⭐+1' },
  dol:  { lore: 'karana',       btn: '🦦 给受伤的海獭喂食',   sb: 15, log: '🐬 驯服獠牙(蓝色海豚岛)',     pend: '⏳ 结交海獭',     done: '✅ 有了朋友',   msg: '🦦 那只叫"獠牙"的海獭,终于肯从你手里接食——卡拉娜笑了,十八年来头一次。 ⚡+15 · ⭐+1' },
  fly:  { lore: 'flyconch',     btn: '🐚 吹响海螺重开集会',   sb: 20, log: '🐚 重整秩序(蝇王)',           pend: '⏳ 吹响海螺',     done: '✅ 火重新亮',   msg: '🐚 海螺一响,散去的孩子又围拢过来,信号火重新烧起——文明,续上了一口气。 ⚡+20 · ⭐+1' },
  uto:  { lore: 'utocity',      btn: '📖 记录理想国的制度',   sb: 15, log: '🏛️ 理想国见闻(乌托邦)',       pend: '⏳ 走访全城',     done: '✅ 已成手记',   msg: '🏛️ 六小时工作、无货币、金夜壶……你都记进本子。完美,还是可怕?留给读者判断。 ⚡+15 · ⭐+1' },
  hux:  { lore: 'moksha',       btn: '🧘 随八哥冥想此时此地', sb: 15, log: '🧘 注意·当下(帕拉岛)',       pend: '⏳ 练一次觉知',   done: '✅ 已然清醒',   msg: '🧘 "注意!此时,此地。"你跟着呼吸,第一次真正地在场。 ⚡+15 · ⭐+1' },
  gul:  { lore: 'lilliput',     btn: '🥚 调停敲蛋战争',       sb: 20, log: '👣 敲蛋和约(格列佛)',         pend: '⏳ 调停两党',     done: '✅ 已促和谈',   msg: '👣 你提议:今后各敲各的那头。大小端两派竟都答应了——天大的仇,原来起于一枚鸡蛋。 ⚡+20 · ⭐+1' },
  nvl:  { lore: 'lostchildren', btn: '✨ 想着快乐的事飞起来', sb: 15, log: '🧚 学会飞行(梦幻岛)',         pend: '⏳ 试着起飞',     done: '✅ 飞过一回',   msg: '✨ 你想起最快乐的一件事,脚尖离了地——原来长大,只是忘了怎么飞。 ⚡+15 · ⭐+1' },
  cor:  { lore: 'coralreef',    btn: '🤿 潜入水下岩洞',       sb: 15, log: '🐠 水下岩洞(珊瑚岛)',         pend: '⏳ 屏气下潜',     done: '✅ 探过秘洞',   msg: '🐠 你屏一口气潜到礁底,钻进一个连海盗都不知道的水下岩洞——里面亮得像撒了金子。 ⚡+15 · ⭐+1' },
  typ:  { lore: 'typeevalley',  btn: '🌴 助汤莫逃回海边',     sb: 20, log: '🌴 逃离山谷(泰皮)',           pend: '⏳ 寻机逃亡',     done: '✅ 已回大海',   msg: '🌴 趁法亚薇拨开禁忌绳,你和汤莫跳上独木舟冲向捕鲸船——文明还是野蛮,他终究做了选择。 ⚡+20 · ⭐+1' },
  tah:  { lore: 'studio',       btn: '🖼️ 在烧毁前抢一幅画',   sb: 20, log: '🎨 抢救杰作(画家岛)',         pend: '⏳ 冲进画室',     done: '✅ 留下一幅',   msg: '🎨 火舌舔上四壁前,你抢出一幅画——斯特里克兰要毁掉的乐园,总算留下一角。 ⚡+20 · ⭐+1' },
  daw:  { lore: 'worldsend',    btn: '🐭 送雷佩契普越浪墙',   sb: 20, log: '🐉 世界尽头(黎明踏浪号)',     pend: '⏳ 划向东方',     done: '✅ 已抵尽头',   msg: '🐭 你目送雷佩契普的小舟越过最后一道浪墙,驶入满是百合与光的国度——它到家了。 ⚡+20 · ⭐+1' },
  rain: { lore: 'missionary',   btn: '☔ 记下这场雨中的对峙', sb: 20, log: '🌧️ 帕果帕果的雨(雨岛)',       pend: '⏳ 旁观牧师',     done: '✅ 已见结局',   msg: '☔ 牧师倒在海滩,汤普森小姐冷笑一声"猪猡"。雨,还在下。你合上了本子。 ⚡+20 · ⭐+1' },
  shu:  { lore: 'shulighthouse',btn: '🗼 登灯塔查明真相',     sb: 20, log: '🌫️ 灯塔的真相(禁闭岛)',     pend: '⏳ 闯进灯塔',     done: '✅ 真相已明',   msg: '🗼 塔顶没有秘密实验,只有考利医生一句"欢迎回来"——那么,谁才是病人? ⚡+20 · ⭐+1' },
  grant: { lore: 'grantbottle', btn: '🍾 捞起瓶中信',         sb: 15, log: '🍾 瓶中信 · 37°11′(南海)',   pend: '⏳ 海上漂着',     done: '✅ 已捞起',     msg: '🍾 三张泡烂的纸,拼出半句坐标:"37°11′——格兰特船长"。你把它收好——总会有一艘邓肯号,为这半句话绕地球一圈。 ⚡+15 · ⭐+1' },
  gala: { lore: 'galafinch',   btn: '📓 为十三种雀喙画一页图谱', sb: 20, log: '🐢 活的博物馆(进化群岛)',   pend: '⏳ 画雀喙图谱',   done: '✅ 图谱已成', msg: '📓 十三种喙,十三把钥匙——同一群雀,被十三座岛各自磨了一万年。你画完最后一笔忽然懂了:造物无需奇迹,时间就是奇迹。 ⚡+20 · ⭐+1' },
  moai: { lore: 'moaigaze',    btn: '🗿 顺着七尊石像的视线望去', sb: 20, log: '🗿 谁在凝望谁(星历仙岛)',   pend: '⏳ 顺视线望星',   done: '✅ 已解凝望', msg: '🗿 七道目光交于夜空同一点——那里没有星。守像人说:\"他们望的是还没升起来的那颗。\"方士在旁边轻轻补了一句:\"蓬莱不可至。凝望,即是抵达。\" ⚡+20 · ⭐+1' },
  fogjail: { lore: 'fogfile',  btn: '🗂️ 把三份 14 号档案对到一起', sb: 20, log: '🌫️ 第十四号(雾中牢岛)', pend: '⏳ 核对档案',     done: '✅ 已对齐(?)', msg: '🗂️ 越狱成功/溺亡/查无此人——三份档案,同一个笔迹。灯塔的光扫过来,一圈,又一圈。你合上卷宗,忽然想不起自己是几号。 ⚡+20 · ⭐+1' },
  venezia: { lore: 'vzmarco', btn: '📜 向可汗描述你走过的群岛', sb: 20, log: '🛶 第五十六种描述(看不见的水城)', pend: '⏳ 向可汗汇报', done: '✅ 已经说破', msg: '📜 你描述了鲸背的岛、白石的都、退位者的庄园……说到一半忽然停住——原来你说的每一座,都是同一座:家。说书人点点头:\"可汗当年,也是这个表情。\" ⚡+20 · ⭐+1' },
  saga: { lore: 'sgskald', btn: '🔥 围着火听一段萨迦', sb: 20, log: '❄️ 末日诗的结尾(冰火萨迦岛)', pend: '⏳ 听一段萨迦', done: '✅ 已闻终章', msg: '🔥 诗人唱到诸神黄昏:狼吞了太阳,海淹了大地——然后他压低嗓子,唱出最后一节:\"大地将再度从海中升起,绿意盎然,瀑布下有鹰掠过。\"火堆噼啪一响。最古老的末日诗,结尾是一个开头。 ⚡+20 · ⭐+1' },
  atl: { lore: 'atplato', btn: '📐 照哲学家的记载丈量环湾', sb: 20, log: '🌀 沉下去才算建成(沉环之岛)', pend: '⏳ 丈量环湾', done: '✅ 数字对不上,影子对上了', msg: '📐 三道水三道墙,数字全对不上——学者不恼,反而笑了:\"两千年人人都量不准。可你看黄昏的湾底,那三圈影子。\"你合上尺子,忽然懂了:有些城市,沉下去才算建成。 ⚡+20 · ⭐+1' },
  sanxian: { lore: 'sxlou', btn: '🌫️ 驾舟追一次蜃楼', sb: 20, log: '🏮 追不上的仙山(三仙岛)', pend: '⏳ 追一次蜃楼', done: '✅ 已然望见', msg: '🌫️ 你朝蓬莱划了一个时辰,它退了一个时辰;你停桨,它也停。守台老道在岸上喊:回来吧——瀛洲也是仙山,你已经站在上面了! ⚡+20 · ⭐+1' },
  shixia: { lore: 'xklast', btn: '📖 在最后一窟添上你的解读', sb: 20, log: '⚔️ 第四种读法(石刻武学岛)', pend: '⏳ 参最后一窟', done: '✅ 已添一解', msg: '📖 三位高人的解读你都记下,又添了第四种——你自己的。写完那刻,石壁微微发烫。守窟的送饭僧瞟了一眼:当年那个不识字的只顾临摹笔画,反倒成了最强。有些文本,不识字的人读得最对。 ⚡+20 · ⭐+1' },
  taozhen: { lore: 'tzbell', btn: '🎵 依宫商角徵羽敲响石钟', sb: 20, log: '🌸 五音开阵(桃阵岛)', pend: '⏳ 敲对五音', done: '✅ 阵已让路', msg: '🎵 五声落定,桃枝无风自分,让出一条只容一人的小径。半山亭的琴声未停,只在句尾多了一个挑音——那是岛主在说:进来吧。 ⚡+20 · ⭐+1' },
  mada: { lore: 'madaark', btn: '📜 清点方舟的乘客名单', sb: 20, log: '🐒 方舟乘客(方舟大陆岛)', pend: '⏳ 清点乘客', done: '✅ 名单已录', msg: '📜 狐猴一百零七种、变色龙占全球一半、八种猴面包树有六种只在这——你合上名单,忽然明白老树医的话:这艘船没有沉,它只是还在航行。 ⚡+20 · ⭐+1' },
  helena: { lore: 'hellear', btn: '👑 在荒野王座旁坐一会儿', sb: 20, log: '👑 退位者的尺度(风中庄园)', pend: '⏳ 陪王坐坐', done: '✅ 已听风说', msg: '👑 风把海吹皱,像吹一张旧地图。你听见椅子上的人说——也可能是风说:\"我曾以为我是一切;后来才知道,我只是一个怕冷的老人。\"退位者的尺度,原来就是人的尺度。 ⚡+20 · ⭐+1' },
  komodo: { lore: 'komstation', btn: '🐉 跟护林员巡一次山', sb: 20, log: '🐉 数龙记(龙蜥荒原)', pend: '⏳ 巡山数龙', done: '✅ 一切正常', msg: '🐉 你们数了十一条龙:六条在晒,四条在睡,一条走了两步又躺下了。护林员在表格里写:一切正常。屠龙诗里没写的是——龙的一生,大部分时候只是想暖和一点。 ⚡+20 · ⭐+1' },
  gunkan: { lore: 'gunkshaft', btn: '⛏️ 乘最后一班罐笼下井', sb: 20, log: '🏭 海底六百米(废矿海城)', pend: '⏳ 下一次井', done: '✅ 签到已补', msg: '⛏️ 罐笼哐当当降到海面之下六百米,巷道尽头竟亮着幽蓝——矿工们早就知道海底迷宫,他们管它叫\"邻居\"。你在签到板上补上名字:全岛撤空五十年,第一个新签到。 ⚡+20 · ⭐+1' },
  soco: { lore: 'soconame', btn: '🌳 把耳朵贴上真名石', sb: 20, log: '🌳 万物的真名(真名植物岛)', pend: '⏳ 听一个真名', done: '✅ 已听见', msg: '🌳 风穿过千年伞盖的那一刻,你听清了那个名字——不是\"龙血树\",是一个更老的词。知其真名,是为了相守,不是为了驱使。你没有说出口:有些名字,听见就够了。 ⚡+20 · ⭐+1' },
  skell: { lore: 'skellbook', btn: '🕯️ 就着风声抄一页书', sb: 20, log: '🕯️ 一页手抄(静默之岩)', pend: '⏳ 抄一页书', done: '✅ 墨已吹干', msg: '🕯️ 那页写着:\"我到林中去,因为我希望谨慎地生活,只面对生活的基本事实。\"修士的字与湖畔人的字隔着一千年,笔迹像同一只手。你搁下笔,风替你把墨吹干。 ⚡+20 · ⭐+1' },
  kilda: { lore: 'kildamail',  btn: '📮 把邮件船放进浪里',       sb: 20, log: '🌬️ 最后的邮件(风暴孤岛)', pend: '⏳ 寄出邮件船',   done: '✅ 已托付大海', msg: '📮 木盒里是最后三十六个人的信:\"我们不是被打败的,我们只是累了。\"你把邮件船推进浪里——两千年的炊烟,就此托付给海流。 ⚡+20 · ⭐+1' },
};
